plugins:
  - jekyll-relative-links
remote-theme: nicoelayda/celeste
markdown: kramdown
title: 4th Artificial Intelligence in Sports (AI-Sports) Workshop
backround: /res/bg.jpg
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
