plugins:
  - jekyll-relative-links
# remote-theme: nicoelayda/celeste
remote-theme: link9596/jekyll-theme-Hydrogen
# baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
description: "Workshop at IEEE International Conference on Multimedia (ICME) 2023"
markdown: kramdown
title: 4th Artificial Intelligence in Sports (AI-Sports) Workshop
backround: /res/bg.jpg
# URL of the Home page image
# index_cover: /res/bg.jpg
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
